name: Echo Minified Files
on:
 workflow_dispatch:
jobs:
 echo_minified_files:
   runs-on: ubuntu-latest
   steps:
   - name: Check out code
     uses: actions/checkout@v2
   - name: List Minified Files
     run: |
       folderPath="./lib"  # Set the path to your JavaScript files folder
       minifiedFiles=("$folderPath"/*-min.js)
       if [ -z "$minifiedFiles" ]
       then
         echo "No minified files found in $folderPath"
       else
         echo "Minified files in $folderPath:"
         for file in $minifiedFiles
         do
           echo "$(basename "$file")"
         done
       fi
