name: Echo Minified Files
on:
 workflow_dispatch:
jobs:
 echo_minified_files:
   runs-on: ubuntu-latest
   steps:
   - name: Check out code
     uses: actions/checkout@v2
   - name: List Minified JavaScript Files
     id: list_files
     run: |
       folderPath="./lib" 
       find "$folderPath" -type f -name "*-min.js" -exec echo {} \;
   - name: Echo Minified Files
     run: |
       filesList=$(echo "${{ steps.list_files.outputs.stdout }}")
       if [ -z "$filesList" ]
       then
         echo "No minified files found in $folderPath"
       else
         echo "Minified files in $folderPath:"
         echo "$filesList"
       fi
